// Список городов
export const MOCK_CITY_LIST = [
  "Delhi",
  "Sydney",
  "Mumbai",
  "New York",
  "London",
  "Tokyo",
  "Paris",
  "Dubai",
  "Singapore",
  "Bangkok",
];

// Mock данные рейсов
export const MOCK_FLIGHTS = [
  // Delhi -> Sydney (One Way рейсы)
  {
    airline: "IndiGo",
    flightNumber: "6E-2341",
    departureCity: "Delhi",
    departureDate: "2025-10-15",
    departureTime: "23:30",
    arrivalCity: "Sydney",
    arrivalDate: null, // One way
    arrivalTime: "18:15",
    duration: "18h 55m",
    stops: 0,
    stopsDisplay: "Non stop",
    price: 980,
    classValue: 1, // Economy
  },
  {
    airline: "Air India",
    flightNumber: "AI-301",
    departureCity: "Delhi",
    departureDate: "2025-10-15",
    departureTime: "08:00",
    arrivalCity: "Sydney",
    arrivalDate: null,
    arrivalTime: "05:30",
    duration: "19h 30m",
    stops: 1,
    stopsDisplay: "1 Stop",
    price: 850,
    classValue: 1,
  },
  {
    airline: "Jet Airways",
    flightNumber: "9W-117",
    departureCity: "Delhi",
    departureDate: "2025-10-15",
    departureTime: "14:45",
    arrivalCity: "Sydney",
    arrivalDate: null,
    arrivalTime: "14:20",
    duration: "21h 35m",
    stops: 2,
    stopsDisplay: "2+ Stops",
    price: 720,
    classValue: 1,
  },
  {
    airline: "SpiceJet",
    flightNumber: "SG-58",
    departureCity: "Delhi",
    departureDate: "2025-10-15",
    departureTime: "11:15",
    arrivalCity: "Sydney",
    arrivalDate: null,
    arrivalTime: "09:45",
    duration: "20h 30m",
    stops: 1,
    stopsDisplay: "1 Stop",
    price: 780,
    classValue: 2, // Premium Economy
  },

  // Sydney -> Delhi (Обратные рейсы для Round Trip)
  {
    airline: "Air Canada",
    flightNumber: "AC-42",
    departureCity: "Sydney",
    departureDate: "2025-10-22", // Дата отправления обратного рейса
    departureTime: "22:00",
    arrivalCity: "Delhi",
    arrivalDate: "2025-10-23", // Дата возвращения (для поиска Round Trip)
    arrivalTime: "06:30",
    duration: "16h 30m",
    stops: 0,
    stopsDisplay: "Non stop",
    price: 1100,
    classValue: 1,
  },
  {
    airline: "American Airlines",
    flightNumber: "AA-127",
    departureCity: "Sydney",
    departureDate: "2025-10-15",
    departureTime: "19:30",
    arrivalCity: "Delhi",
    arrivalDate: "2025-10-22",
    arrivalTime: "14:45",
    duration: "17h 15m",
    stops: 1,
    stopsDisplay: "1 Stop",
    price: 950,
    classValue: 1,
  },
  {
    airline: "Asiana Airlines",
    flightNumber: "OZ-746",
    departureCity: "Sydney",
    departureDate: "2025-10-15",
    departureTime: "10:00",
    arrivalCity: "Delhi",
    arrivalDate: "2025-10-25",
    arrivalTime: "08:30",
    duration: "20h 30m",
    stops: 2,
    stopsDisplay: "2+ Stops",
    price: 820,
    classValue: 1,
  },

  // Mumbai -> Tokyo (дополнительные маршруты)
  {
    airline: "IndiGo",
    flightNumber: "6E-5012",
    departureCity: "Mumbai",
    departureDate: "2025-10-20",
    departureTime: "02:00",
    arrivalCity: "Tokyo",
    arrivalDate: null,
    arrivalTime: "12:30",
    duration: "8h 30m",
    stops: 0,
    stopsDisplay: "Non stop",
    price: 650,
    classValue: 1,
  },
  {
    airline: "Air India",
    flightNumber: "AI-307",
    departureCity: "Mumbai",
    departureDate: "2025-10-20",
    departureTime: "23:45",
    arrivalCity: "Tokyo",
    arrivalDate: null,
    arrivalTime: "11:15",
    duration: "9h 30m",
    stops: 1,
    stopsDisplay: "1 Stop",
    price: 580,
    classValue: 3, // Business
  },

  // Tokyo -> Mumbai (обратные)
  {
    airline: "Air India",
    flightNumber: "AI-308",
    departureCity: "Tokyo",
    departureDate: "2025-10-25",
    departureTime: "13:00",
    arrivalCity: "Mumbai",
    arrivalDate: "2025-10-27",
    arrivalTime: "19:30",
    duration: "8h 30m",
    stops: 0,
    stopsDisplay: "Non stop",
    price: 700,
    classValue: 1,
  },

  // Delhi -> London
  {
    airline: "Air India",
    flightNumber: "AI-161",
    departureCity: "Delhi",
    departureDate: "2025-11-01",
    departureTime: "02:30",
    arrivalCity: "London",
    arrivalDate: null,
    arrivalTime: "07:15",
    duration: "9h 45m",
    stops: 0,
    stopsDisplay: "Non stop",
    price: 1200,
    classValue: 1,
  },
  {
    airline: "Jet Airways",
    flightNumber: "9W-118",
    departureCity: "Delhi",
    departureDate: "2025-11-01",
    departureTime: "09:00",
    arrivalCity: "London",
    arrivalDate: null,
    arrivalTime: "14:30",
    duration: "10h 30m",
    stops: 1,
    stopsDisplay: "1 Stop",
    price: 980,
    classValue: 4, // First class
  },

  // London -> Delhi (обратные)
  {
    airline: "Air India",
    flightNumber: "AI-162",
    departureCity: "London",
    departureDate: "2025-11-01",
    departureTime: "21:00",
    arrivalCity: "Delhi",
    arrivalDate: "2025-11-10",
    arrivalTime: "10:30",
    duration: "8h 30m",
    stops: 0,
    stopsDisplay: "Non stop",
    price: 1250,
    classValue: 1,
  },

  // New York -> Dubai
  {
    airline: "American Airlines",
    flightNumber: "AA-50",
    departureCity: "New York",
    departureDate: "2025-10-18",
    departureTime: "22:30",
    arrivalCity: "Dubai",
    arrivalDate: null,
    arrivalTime: "19:45",
    duration: "12h 15m",
    stops: 0,
    stopsDisplay: "Non stop",
    price: 1400,
    classValue: 2,
  },
  {
    airline: "Multiple Airlines",
    flightNumber: "MX-001",
    departureCity: "New York",
    departureDate: "2025-10-18",
    departureTime: "10:00",
    arrivalCity: "Dubai",
    arrivalDate: null,
    arrivalTime: "12:30",
    duration: "15h 30m",
    stops: 2,
    stopsDisplay: "2+ Stops",
    price: 890,
    classValue: 1,
  },

  // Dubai -> New York (обратные)
  {
    airline: "American Airlines",
    flightNumber: "AA-51",
    departureCity: "Dubai",
    departureDate: "2025-10-18",
    departureTime: "03:00",
    arrivalCity: "New York",
    arrivalDate: "2025-10-25",
    arrivalTime: "10:15",
    duration: "14h 15m",
    stops: 0,
    stopsDisplay: "Non stop",
    price: 1500,
    classValue: 2,
  },

  // Paris -> Singapore
  {
    airline: "Air Canada",
    flightNumber: "AC-890",
    departureCity: "Paris",
    departureDate: "2025-11-05",
    departureTime: "13:20",
    arrivalCity: "Singapore",
    arrivalDate: null,
    arrivalTime: "08:45",
    duration: "13h 25m",
    stops: 1,
    stopsDisplay: "1 Stop",
    price: 1100,
    classValue: 3,
  },

  // Singapore -> Paris (обратные)
  {
    airline: "Air Canada",
    flightNumber: "AC-891",
    departureCity: "Singapore",
    departureDate: "2025-11-05",
    departureTime: "23:30",
    arrivalCity: "Paris",
    arrivalDate: "2025-11-15",
    arrivalTime: "07:20",
    duration: "13h 50m",
    stops: 1,
    stopsDisplay: "1 Stop",
    price: 1150,
    classValue: 3,
  },
];
